name: Auto Add to Project

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

permissions: {}

jobs:
  add-to-project:
    name: Add to Project Board
    runs-on: ubuntu-latest
    steps:
      - name: Add to PowerQuota Project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/esoltys/projects/4
          github-token: ${{ secrets.PROJECTS_TOKEN || secrets.GITHUB_TOKEN }}
